# DO NOT EDIT BY HAND: is automatically re-generated by make.py
set shell := ["python", "./make.py"]
default:
    @{{"--help"}}

clean:
    @clean

html:
    @html

serve:
    @serve

dirhtml:
    @dirhtml

singlehtml:
    @singlehtml

pickle:
    @pickle

json:
    @json

htmlhelp:
    @htmlhelp

qthelp:
    @qthelp

applehelp:
    @applehelp

devhelp:
    @devhelp

epub:
    @epub

latex:
    @latex

latexpdf:
    @latexpdf

latexpdfja:
    @latexpdfja

text:
    @text

man:
    @man

texinfo:
    @texinfo

info:
    @info

gettext:
    @gettext

changes:
    @changes

linkcheck:
    @linkcheck

doctest:
    @doctest

coverage:
    @coverage

xml:
    @xml

pseudoxml:
    @pseudoxml

lint:
    @lint

ruff:
    @ruff

mypy:
    @mypy

pyright:
    @pyright

test_full:
    @test_full

test:
    @test

