# DO NOT EDIT BY HAND: is automatically re-generated by make.py
.PHONY: default
default:
	python ./make.py --help

.PHONY: clean
clean:
	python ./make.py clean

.PHONY: html
html:
	python ./make.py html

.PHONY: serve
serve:
	python ./make.py serve

.PHONY: dirhtml
dirhtml:
	python ./make.py dirhtml

.PHONY: singlehtml
singlehtml:
	python ./make.py singlehtml

.PHONY: pickle
pickle:
	python ./make.py pickle

.PHONY: json
json:
	python ./make.py json

.PHONY: htmlhelp
htmlhelp:
	python ./make.py htmlhelp

.PHONY: qthelp
qthelp:
	python ./make.py qthelp

.PHONY: applehelp
applehelp:
	python ./make.py applehelp

.PHONY: devhelp
devhelp:
	python ./make.py devhelp

.PHONY: epub
epub:
	python ./make.py epub

.PHONY: latex
latex:
	python ./make.py latex

.PHONY: latexpdf
latexpdf:
	python ./make.py latexpdf

.PHONY: latexpdfja
latexpdfja:
	python ./make.py latexpdfja

.PHONY: text
text:
	python ./make.py text

.PHONY: man
man:
	python ./make.py man

.PHONY: texinfo
texinfo:
	python ./make.py texinfo

.PHONY: info
info:
	python ./make.py info

.PHONY: gettext
gettext:
	python ./make.py gettext

.PHONY: changes
changes:
	python ./make.py changes

.PHONY: linkcheck
linkcheck:
	python ./make.py linkcheck

.PHONY: doctest
doctest:
	python ./make.py doctest

.PHONY: coverage
coverage:
	python ./make.py coverage

.PHONY: xml
xml:
	python ./make.py xml

.PHONY: pseudoxml
pseudoxml:
	python ./make.py pseudoxml

.PHONY: lint
lint:
	python ./make.py lint

.PHONY: ruff
ruff:
	python ./make.py ruff

.PHONY: mypy
mypy:
	python ./make.py mypy

.PHONY: pyright
pyright:
	python ./make.py pyright

.PHONY: test_full
test_full:
	python ./make.py test_full

.PHONY: test
test:
	python ./make.py test

