from __future__ import annotations

from typing import Protocol, runtime_checkable, TYPE_CHECKING

from arcade.types import BufferProtocol

if TYPE_CHECKING:
    from .context import Context

@runtime_checkable
class Buffer(Protocol):

    @property
    def ctx(self) -> Context: ...
    def delete(self) -> None: ...

    @property
    def size(self) -> int: ...

    def read(self, size: int = -1, offset: int = 0) -> bytes: ...
    def write(self, data: BufferProtocol, offset: int = 0) -> None: ...
    def copy_from_buffer(self, source: Buffer, size=-1, offset=0, source_offset=0) -> None: ...
    def orphan(self, size: int = -1, double: bool = False) -> None: ...
    def bind_to_uniform_block(self, binding: int = 0, offset: int = 0, size: int = -1) -> None: ...
    def bind_to_storage_buffer(self, binding: int = 0, offset: int = 0, size: int = -1) -> None: ...