# Supported types:
#
# Arcade color: BLACK -> arcade.color.BLACK
# RGB color: RGB string 255, 255, 255 -> (255,255,255)
# HEX color: FFFFFF or FFF -> (0,0,0)
# Font names: (YAML List) ['Calibri', 'Arial'] -> ['Calibri', 'Arial']
# Empty value: "" or '' or null -> None
# Path: './images/ABC': Path('./images/ok_button.png')
#
# Returns value as parsed by PyYaml


globals:
  # setting font global is a good idea ;)
  font_name:
    - 'Calibri'
    - 'Arial'


label:
  font_size: 22
  font_color: GRAY
  font_color_hover: LIGHT_GRAY
  font_color_press: WHITE


flatbutton:
  font_size: 22
  border_width: 2
  vmargin: 15 # margin between text and border (top and bottom)

  font_color: WHITE
  border_color: None
  bg_color: 21,19,21

  font_color_hover: WHITE
  border_color_hover: WHITE
  bg_color_hover: 21,19,21

  font_color_press: BLACK
  bg_color_press: WHITE
  border_color_press: WHITE


ghostflatbutton:
  font_size: 22
  border_width: 2
  vmargin: 15 # margin between text and border (top and bottom)

  font_color: WHITE
  border_color: 21,19,21
  bg_color: None

  font_color_hover: WHITE
  border_color_hover: 21,19,21
  bg_color_hover: 21,19,21

  font_color_press: BLACK
  border_color_press: 21,19,21
  bg_color_press: WHITE


inputbox:
  font_size: 22
  border_width: 2
  margin_left: 15 # margin between text and left edge
  vmargin: 15 # margin between text and border (top and bottom)

  font_color: WHITE
  border_color: WHITE
  bg_color: 21, 19, 21

  font_color_hover: WHITE
  border_color_hover: WHITE
  bg_color_hover: GRAY

  font_color_focus: BLACK
  border_color_focus: WHITE
  bg_color_focus: GRAY

imagebutton:
  font_size: 22
  font_color: WHITE
  font_color_hover: WHITE
  font_color_press: WHITE

toggle:
  color_true: WHITE
  bg_color_true: BLUE

  color_false: WHITE
  bg_color_false: GRAY
