import OpenGL.GLUT as GLUT

# Special keys
F1 = GLUT.GLUT_KEY_F1
F2 = GLUT.GLUT_KEY_F2
F3 = GLUT.GLUT_KEY_F3
F4 = GLUT.GLUT_KEY_F4
F5 = GLUT.GLUT_KEY_F5
F6 = GLUT.GLUT_KEY_F6
F7 = GLUT.GLUT_KEY_F7
F8 = GLUT.GLUT_KEY_F8
F9 = GLUT.GLUT_KEY_F9
F10 = GLUT.GLUT_KEY_F10
F11 = GLUT.GLUT_KEY_F11
F12 = GLUT.GLUT_KEY_F12
LEFT = GLUT.GLUT_KEY_LEFT
UP = GLUT.GLUT_KEY_UP
RIGHT = GLUT.GLUT_KEY_RIGHT
DOWN = GLUT.GLUT_KEY_DOWN
PAGE_UP = GLUT.GLUT_KEY_PAGE_UP
PAGE_DOWN = GLUT.GLUT_KEY_PAGE_DOWN
HOME = GLUT.GLUT_KEY_HOME
END = GLUT.GLUT_KEY_END
INSERT = GLUT.GLUT_KEY_INSERT
