name: Bump Version

on:
  workflow_dispatch:

jobs:
  # --- Bump version
  bump-version:

    runs-on: ubuntu-latest
    environment: deploy-pypi-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.MY_TOKEN }}
      - name: Bump versions
        uses: remorses/bump-version@js
        with:
            version_file: ./arcade/VERSION
            prerelease_tag: rc
        env:
            GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
