# This does code inspection and checks to make sure building of docs works

on:
  push:
    branches: [development, maintenance]
  pull_request:
    branches: [development, maintenance]
  workflow_dispatch:

jobs:

  build:
    name: Code Inspections
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Sync UV project
        run: uv sync

      - name: Formatting (Ruff)
        run: uv run make.py format --check

      - name: Linting (Ruff)
        run: uv run make.py ruff-check

      - name: Type Checking (MyPy)
        run: uv run make.py mypy

      - name: Type Checking (Pyright)
        run: uv run make.py pyright
