# Builds the doc in PRs

name: Docs Build

on:
  push:
    branches: [development, maintenance]
  pull_request:
    branches: [development, maintenance]
  workflow_dispatch:

jobs:

  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Sync UV Project
        run: uv sync

      - name: build-docs
        run: uv run make.py docs-full
