name: Distribute build to PyPi Production

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    # This environment is defined in GitHub to hold our secrets
    environment: deploy-pypi-prod

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          python3 -m pip install pyogg pymunk
          # Pull dev packages from 
          python3 -m pip install -e .

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: |
          python3 setup sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PROD_TOKEN }}
          TWINE_REPOSITORY: pypi