name: PyTest

on:
  push:
    branches: [development, maintenance]
  pull_request:
    branches: [development, maintenance]
  workflow_dispatch:

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Update apt
        run: sudo apt-get update

      # xvfb is used to run "headless" by providing a virtual X server
      # ffmpeg is used for handling mp3 files in some of our tests
      - name: Install xvfb and ffmpeg
        run: sudo apt-get install xvfb ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Sync UV project
        run: uv sync

      - name: Run tests
        env:
          PYGLET_BACKEND: opengl
          REPL_ID: hello # Arcade checks for this to disable anti-aliasing
        run: |
          xvfb-run --auto-servernum uv run arcade
          xvfb-run --auto-servernum uv run pytest --maxfail=10