name: Type completeness report

on:
  push:
    branches: [development, maintenance]
  pull_request:
    branches: [development, maintenance]
  workflow_dispatch:

jobs:

  verifytypes:
    name: Verify types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64

      - name: Install
        id: install
        run: |
          python -m pip install .[dev]
      - name: "code-inspection: pyright --verifytypes"
        # Suppress exit code because we do not expect to reach 100% type completeness any time soon
        run: |
          python -m pyright --verifytypes arcade || true
